### ISSUE TITLE
A bug in <% LifeOS.Project.snapshot() %>

### ISSUE THREAD

**Issue by jmjeong** [quanru/obsidian-lifeos#88]
Sometime this macro won't expanded with the project list. 
It happens from time to time, so I don't know the exact reproducible scenario. 

This is a sample in daily note (eg. 2024-09-22). It was expanded in the yesterday's daily note.

<img width="329" alt="Screenshot of Obsidian at Sep 22, 2024 at 3_11_35 PM" src="https://github.com/user-attachments/assets/b2120497-1fa2-4485-ae60-93aaf6b9d453">

**Comment by quanru** [comment]
It is recommended to work with [Templater](https://silentvoid13.github.io/Templater/), Be sure to enable the "Trigger Templater on new file creation" option of the Templater plugin, so that you can use the template variables and functions provided by [Templater](https://silentvoid13.github.io/Templater/).

[#](https://lifeos.vip/plugin/life-os.html#create-periodic-notes)

**Comment by quanru** [comment]
Is it a must-see scene?

**Comment by jmjeong** [comment]
From the daily notes, it is better to browse the current project list I am interested in.

**Comment by quanru** [comment]
I can't reproduce it
